version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,sqs
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_REMOTE_DOCKER=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app: 
    build: .
    volumes: 
      - .:/src
      - nodemodules:/src/node_modules
    restart: on-failure
    ports:
      - 3000:3000
    links:
      - localstack
    depends_on:
      - localstack
    environment: 
      LOCALSTACK_HOST: localstack
      S3_PORT: 4566
      SQS_PORT: 4566

volumes:
  nodemodules: {}
