service: api-manager

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

  apiKeys:
    - free: ${file(./default-costumer.js):private}
    - paid: 
      - otallyto@gmail.com
  usagePlan:
    - free: 
        quota:
          limit: 10
          period: MONTH
        throttle:
          burstLimit: 200
          rateLimit: 100
    - paid: 
        quota:
          limit: 1000
          period: DAY
        throttle:
          burstLimit: 400
          rateLimit: 50
package:
  excludeDevDependencies: true

plugins:
  - serverless-offline


functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: hello
         method: get
         private: true
