service: vpc-aurora-serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    MYSQL_HOST: ${env:MYSQL_HOST, "serverlesscourse.cluster-cdboaawuxhxu.us-east-1.rds.amazonaws.com"}
    MYSQL_PORT: ${env:MYSQL_PORT, "3306"}
    MYSQL_USER: ${env:MYSQL_USER, "otallyto"}
    MYSQL_PASS: ${env:MYSQL_PASS, "abc12345678"}
    MYSQL_DATABASE: ${env:MYSQL_DATABASE, "heroes"}
  vpc:
    securityGroupIds:
      - sg-370b0805
    subnetIds:
      - subnet-feca9fb3
      - subnet-7e4dc818
      - subnet-480f8917
      - subnet-3af78834
      - subnet-809159b1
      - subnet-3ec0431f
package:
  excludeDevDependencies: true

plugins:
 - serverless-offline

functions:
  hello:
    handler: src/index.handler
    events:
      - http:
          method: any
          path: hello
