service: lambda-environment

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, "qa"}
  environment:
    ${file(./config/env.${self:provider.stage}.json)}
  iamRoleStatements:
    ${file(./config/serverless/db.iam.role.yml)}

custom: 
  schedulerRate: rate(1 minute)
  enabled: true
  tableName: ${self:provider.environment.DbTableName}
  DbWriteCapacityUnits: ${self:provider.environment.DbWriteCapacityUnits}
  DbReadCapacityUnits: ${self:provider.environment.DbReadCapacityUnits}

resources:
  Resources:
    ${file(./config/serverless/rosources/dynamo.hero.table.yml)}

functions:
  commit-message-scheduler:
    handler: handler.scheduler
    events:
    - schedule:
        rate: ${self:custom.schedulerRate}
        enabled: ${self:custom.enabled}
        name: schedule-commit-message-${self:provider.stage}
        description: get commit messages each minute



